### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by ssalggnikool**

### CODE REVIEW

**Review by stereoDotLuigi — CHANGES_REQUESTED** [review]
Weird that you translated some Turkish translations to English.

**Comment by ssalggnikool** [comment]
> Weird that you translated some Turkish translations to English.
> 
> 

Crowdin does it automatically when I change an english translation.

**Comment by stereoDotLuigi** [comment]
Anyways, I checked the translations. They're all good now I guess.
Will this Turkish translation give me a place in credits page? Would like to see myself there.

image

**Comment by ssalggnikool** [comment]
Yeah sure, I'll add you in a bit

**Pull request merged**
