### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by itsnebulalol**

### CODE REVIEW

**Comment by ommiusesarch** [comment]
shut the fuck up fatherless mf.

flower should die in hell, ruined palera1n tbh even though im banned

fuck you all!
ommi

**Comment by ommiusesarch** [comment]
shut the fuck up fatherless mf.

flower should die in hell, ruined palera1n tbh even though im banned

fuck you all!
ommi

**Comment by ommiusesarch** [comment]
shut the fuck up fatherless mf.

flower should die in hell, ruined palera1n tbh even though im banned

fuck you all!
ommi

**Comment by ommiusesarch** [comment]
shut the fuck up fatherless mf.

flower should die in hell, ruined palera1n tbh even though im banned

fuck you all!
ommi

**Comment by ommiusesarch** [comment]
shut the fuck up fatherless mf.

flower should die in hell, ruined palera1n tbh even though im banned

fuck you all!
ommi

**Comment by ommiusesarch** [comment]
shut the fuck up fatherless mf.

flower should die in hell, ruined palera1n tbh even though im banned

fuck you all!
ommi

**Comment by ommiusesarch** [comment]
shut the fuck up fatherless mf.

flower should die in hell, ruined palera1n tbh even though im banned

fuck you all!
ommi

**Comment by ommiusesarch** [comment]
shut the fuck up fatherless mf.

flower should die in hell, ruined palera1n tbh even though im banned

fuck you all!
ommi

**Comment by ommiusesarch** [comment]
shut the fuck up fatherless mf.

flower should die in hell, ruined palera1n tbh even though im banned

fuck you all!
ommi

**Comment by ommiusesarch** [comment]
shut the fuck up fatherless mf.

flower should die in hell, ruined palera1n tbh even though im banned

fuck you all!
ommi

**Comment by ommiusesarch** [comment]
shut the fuck up fatherless mf.

flower should die in hell, ruined palera1n tbh even though im banned

fuck you all!
ommi

**Comment by ommiusesarch** [comment]
L

**Comment by flowerible** [comment]
get a life.

**Pull request merged**
