### PR TITLE
Update CreditsSheetView.swift

### PR DESCRIPTION
**Pull request by m00nl1ghts**
feat: add Azreal credit for fixed Cydia .deb

- m00nl1ghts

### CODE REVIEW

**Comment by m00nl1ghts** [comment]
people have credit for other simple things too lol its up to llsc12 to merge it or not

**Comment by m00nl1ghts** [comment]
try reading my comment again and come back 👍

**Comment by m00nl1ghts** [comment]
it's not my fault you have a different point of view to mine. if llsc12 doesn't want to merge it, thats up to him, not to you to "berate" me over a github pull request 💀

**Comment by ja1dan** [comment]
chill out fr

**Comment by m00nl1ghts** [comment]
i'm not the one going all crazy over a pr 🤷

**Comment by ja1dan** [comment]
this pr is reasonable because this person feels that they deserve credit for something that they did for the project. no need to argue about it, if you don't like it then shrug and move on

**Pull request closed without merging**
